CUDA_VISIBLE_DEVICES=0 python pretrain.py \
    seed=42 \
    bonus=0.5 \
    task=quadruped_jump \
    supervised=true \
    agent=ddpg \
    agent.nstep=1 \
    agent.batch_size=1024 \
    obs_type=states \
    action_repeat=1 \
    num_train_frames=10000010 \
    replay_buffer_size=200000 \
    replay_buffer_num_workers=4 \
    save_replay_buffer=True \
    project=MaskDP_state_data \
    use_wandb=True &