defaults:
  - agent: mdp_multitask # can be mdp_goal or mdp_prompt
  - override hydra/launcher: submitit_local

# unsupervised exploration
pretrained_data: mixed # [mixed, semi, sup, unsup]
finetuned_data: expert # [mixed, semi, sup, unsup, expert]
# task settings
task: [quadruped_run,quadruped_walk]
discount: 0.99
# train settings
num_grad_steps: 40000
log_every_steps: 500
# eval
eval_every_steps: 5000
num_eval_episodes: 10
# snapshot
snapshot_ts: 400000
snapshot_base_dir: ../../../output/2022.05.12/051229_mdp/snapshot
# dataset
replay_buffer_dir: /shared/fangchen/rl_data_collection/unsup
replay_buffer_size: 1000000
replay_buffer_num_workers: 16
batch_size: ${agent.batch_size}

# misc
seed: 1
device: cuda
save_video: true
use_tb: true
use_wandb: true
project: fangchen-eval-mdp-mtrl
notes: "finetune"
mt: true


hydra:
  run:
    dir: /shared/fangchen/models/mt/${now:%Y.%m.%d}/${now:%H%M%S}_${agent.name}
