defaults:
  - agent: mdp_rl # can be mdp_goal or mdp_prompt
  - override hydra/launcher: submitit_local

# unsupervised exploration
finetuned_data: unsup # [mixed, semi, sup, unsup, expert]
# task settings
task: walker_walk
discount: 0.99
# train settings
num_grad_steps: 40000
log_every_steps: 500
# eval
eval_every_steps: 5000
num_eval_episodes: 10
# snapshot
snapshot_ts: 400000
snapshot_base_dir: ../../../output/2022.05.12/051229_mdp/snapshot
# dataset
replay_buffer_dir: /path/to/maskdp_eval/unsup
replay_buffer_size: 1000000
replay_buffer_num_workers: 16
batch_size: ${agent.batch_size}

# misc
seed: 1
device: cuda
save_video: true
use_tb: true
use_wandb: true
project: fangchen-eval-mdp-mtrl
notes: "finetune"


hydra:
  run:
    dir: /path/to/finetune/${now:%Y.%m.%d}/${now:%H%M%S}_${agent.name}
