#!/usr/bin/env bash
CUDA_VISIBLE_DEVICES=1 python pretrain_mdp_mt.py \
    agent=mdp \
    agent.batch_size=384 \
    agent.transformer_cfg.traj_length=64 \
    agent.transformer_cfg.loss="total" \
    agent.transformer_cfg.n_embd=256 \
    agent.transformer_cfg.n_head=4 \
    agent.transformer_cfg.n_enc_layer=3 \
    agent.transformer_cfg.n_dec_layer=2 \
    agent.transformer_cfg.norm='l2' \
    num_grad_steps=400010 \
    task=quadruped_run \
    snapshot_dir=snapshot \
    resume=false\
    exp_name='final_mt'\
    project=final_mt_mdp \
    use_wandb=True &
sleep 30
CUDA_VISIBLE_DEVICES=2 python pretrain_mdp_mt.py \
    agent=mdp \
    agent.batch_size=384 \
    agent.transformer_cfg.traj_length=64 \
    agent.transformer_cfg.loss="total" \
    agent.transformer_cfg.n_embd=256 \
    agent.transformer_cfg.n_head=4 \
    agent.transformer_cfg.n_enc_layer=3 \
    agent.transformer_cfg.n_dec_layer=2 \
    agent.transformer_cfg.norm='l2' \
    num_grad_steps=400010 \
    task=walker_run \
    snapshot_dir=snapshot \
    resume=false\
    exp_name='final_mt'\
    project=final_mt_mdp \
    use_wandb=True &
sleep 30
CUDA_VISIBLE_DEVICES=3 python pretrain_mdp_mt.py \
    agent=mdp \
    agent.batch_size=384 \
    agent.transformer_cfg.traj_length=64 \
    agent.transformer_cfg.loss="total" \
    agent.transformer_cfg.n_embd=256 \
    agent.transformer_cfg.n_head=4 \
    agent.transformer_cfg.n_enc_layer=3 \
    agent.transformer_cfg.n_dec_layer=2 \
    agent.transformer_cfg.norm='l2' \
    num_grad_steps=400010 \
    task=cheetah_run \
    snapshot_dir=snapshot \
    resume=false\
    exp_name='final_mt'\
    project=final_mt_mdp \
    use_wandb=True &
sleep 30