# @package agent
_target_: agent.diayn.DIAYNAgent
name: diayn
obs_type: ??? # to be specified later
obs_shape: ??? # to be specified later
action_shape: ??? # to be specified later
device: ${device}
lr: 1e-4
critic_target_tau: 0.01
update_every_steps: 2
use_tb: ${use_tb}
use_wandb: ${use_wandb}
num_expl_steps: ??? # to be specified later
hidden_dim: 1024
feature_dim: 50
stddev_schedule: 0.2
stddev_clip: 0.3
skill_dim: 16
diayn_scale: 1.0
update_skill_every_step: 50
nstep: 3
batch_size: 1024
init_critic: true
update_encoder: ${update_encoder}
supervised: ${supervised} # supervised dataset
bonus: ${bonus}