# @package agent
_target_: agent.gpt_multitask.MTGPTAgent
name: gpt_mt
obs_shape: ??? # to be specified later
action_shape: ??? # to be specified later
device: ${device}
lr: 1e-4
critic_target_tau: 0.01
use_tb: ${use_tb}
stddev_schedule: 0.2
stddev_clip: 0.3
nstep: 1
batch_size: 128 # 256 for pixels
has_next_action: False
finetune_actor: 'encoder'
finetune_critic: 'encoder'
attn_length: 1
transformer_cfg:
  n_embd: 128
  n_head: 2
  n_layer: 5
  embd_pdrop: 0
  resid_pdrop: 0
  attn_pdrop: 0
  traj_length: 12
  norm: 'l2'